name: Version

on:
  pull_request:
    branches: [ master ]
    types: [ closed ]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, '[RELEASE]')"

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      - run: git config --global user.name 'Nic'
      - run: git config --global user.email 'Nick376@hotmail.fr'
      - run: npm version patch -m "[RELEASE] %s"
      - run: git push
